title: My Resume

theme_skin: blue

# Tracker
analytics: G-8G25CZL659

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development